/* Generated By:JJTree: Do not edit this line. ASTEqualityExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package computeparser;

public
class ASTEqualityExpression extends SimpleNode {
  private	String opCode;
  public ASTEqualityExpression(int id) {
    super(id);
  }

  public ASTEqualityExpression(ComputeGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ComputeGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setOpCode(String image) {
	opCode = image;
	
}

public String getOpCode() {
	return opCode;
}
}
/* JavaCC - OriginalChecksum=955c813a7621ab2ddcb47473f84228c6 (do not edit this line) */
