/* Generated By:JJTree: Do not edit this line. ASTMessageState.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package computeparser;

public
class ASTMessageState extends SimpleNode {
  private MessageState state;

public ASTMessageState(int id) {
    super(id);
  }

  public ASTMessageState(ComputeGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ComputeGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setState(String image) {
	if("on".equals(image)) {
		state = MessageState.ON;
	} else {
		state = MessageState.OFF;
	}
}
public MessageState getState() {
	return state;
}
}
/* JavaCC - OriginalChecksum=7dd53844ff5f2f8e759d23471c348aee (do not edit this line) */
