/* Generated By:JJTree: Do not edit this line. ASTPrimaryIntegerExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package computeparser;

public
class ASTPrimaryIntegerExpression extends SimpleNode {
	public enum OpCodes {
		EXPRESSION,
		INTEGER,
		COUNT
	}
	OpCodes opCode;
	private int value;
  public ASTPrimaryIntegerExpression(int id) {
    super(id);
  }

  public ASTPrimaryIntegerExpression(ComputeGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ComputeGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setOpCode(OpCodes o) {
	opCode = o;
}
public OpCodes getOpCode() {
	return opCode;
}

public void setInt(String image) {
	value = Integer.parseInt(image);
}
public int getInt() {
	return value;
}
}
/* JavaCC - OriginalChecksum=cd1cafa602d4ed7a73c6dcfb360ff7ba (do not edit this line) */
