/* Generated By:JJTree: Do not edit this line. ASTTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package computeparser;

public
class ASTTime extends SimpleNode {
	private int time;
  public ASTTime(int id) {
    super(id);
  }

  public ASTTime(ComputeGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ComputeGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setTime(String image) {
	time = Integer.parseInt(image);
}
public int getTime() {
	return time;
}
}
/* JavaCC - OriginalChecksum=7abb95cf8ec23edd6e390ac28c019251 (do not edit this line) */
