/* Generated By:JJTree: Do not edit this line. ASTUnaryBooleanExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package computeparser;

public
class ASTUnaryBooleanExpression extends SimpleNode {
	private boolean notted=false;
  public ASTUnaryBooleanExpression(int id) {
    super(id);
  }

  public ASTUnaryBooleanExpression(ComputeGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ComputeGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public void setOp(boolean b) {
	notted = b;
}
public boolean getOp() {
	return notted;
}
}
/* JavaCC - OriginalChecksum=9fc13818f3983c92165273716e2020a9 (do not edit this line) */
